package model

// Code generated by go-bridget/mig. DO NOT EDIT.

import (
	"fmt"
	"strings"
	"time"
)

// QueryOption is implemented by each data model type.
type QueryOption interface {
	WithTable(name string) QueryOption
	WithColumns(cols []string) QueryOption
	WithWhere(clause string) QueryOption
	WithOrderBy(clause string) QueryOption
	WithLimit(start, offset int) QueryOption
	WithStatement(stmt string) QueryOption
}

// QueryConfig is a function-chaining SQL statement type.
type QueryConfig struct {
	Table       string
	Columns     []string
	Where       string
	OrderBy     string
	LimitStart  int
	LimitOffset int
	Statement   string
}

// WithTable will set the table name for the query.
func (q *QueryConfig) WithTable(name string) QueryOption {
	q.Table = name
	return q
}

// WithColumns will set the columns to use for the query.
func (q *QueryConfig) WithColumns(cols []string) QueryOption {
	q.Columns = cols
	return q
}

// WithWhere will set the where condition for the query.
func (q *QueryConfig) WithWhere(clause string) QueryOption {
	q.Where = clause
	return q
}

// WithOrderBy will set the order by clause for the query.
func (q *QueryConfig) WithOrderBy(clause string) QueryOption {
	q.OrderBy = clause
	return q
}

// WithLimit will set the limit clause parameters for the query.
func (q *QueryConfig) WithLimit(start, offset int) QueryOption {
	q.LimitStart = start
	q.LimitOffset = offset
	return q
}

// WithStatement will change the statement for the query.
func (q *QueryConfig) WithStatement(stmt string) QueryOption {
	q.Statement = stmt
	return q
}

// WithTable will set the table name for the query.
func WithTable(name string) QueryOption {
	return &QueryConfig{Table: name}
}

// WithColumns will set the columns to use for the query.
func WithColumns(cols []string) QueryOption {
	return &QueryConfig{Columns: cols}
}

// WithWhere will set the where condition for the query.
func WithWhere(clause string) QueryOption {
	return &QueryConfig{Where: clause}
}

// WithOrderBy will set the order by clause for the query.
func WithOrderBy(clause string) QueryOption {
	return &QueryConfig{OrderBy: clause}
}

// WithLimit will set the limit clause parameters for the query.
func WithLimit(start, offset int) QueryOption {
	return &QueryConfig{LimitStart: start, LimitOffset: offset}
}

// WithStatement will change the statement for the query.
func WithStatement(stmt string) QueryOption {
	return &QueryConfig{Statement: stmt}
}

// Apply will use passed query options to populate the query.
func (q *QueryConfig) Apply(opts ...QueryOption) *QueryConfig {
	cfg := *q
	for _, opt := range opts {
		o := opt.(*QueryConfig)
		if o.Table != "" {
			cfg.Table = o.Table
		}
		if len(o.Columns) > 0 {
			cfg.Columns = o.Columns
		}
		if o.Where != "" {
			cfg.Where = o.Where
		}
		if o.OrderBy != "" {
			cfg.OrderBy = o.OrderBy
		}
		if o.LimitOffset > 0 {
			cfg.LimitStart = o.LimitStart
			cfg.LimitOffset = o.LimitOffset
		}
		if o.Statement != "" {
			cfg.Statement = o.Statement
		}
	}
	return &cfg
}

// Jobs generated for db table `jobs`.
type Jobs struct {
	// Name
	Name string `db:"name" json:"name"`

	// Description
	Description string `db:"description" json:"description"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`

	// Updated At
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`

	// Deleted At
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

// GetName will return the value of Name.
func (j *Jobs) GetName() string { return j.Name }

// SetName sets Name to the provided value.
func (j *Jobs) SetName(val string) { j.Name = val }

// GetDescription will return the value of Description.
func (j *Jobs) GetDescription() string { return j.Description }

// SetDescription sets Description to the provided value.
func (j *Jobs) SetDescription(val string) { j.Description = val }

// GetCreatedAt will return the value of CreatedAt.
func (j *Jobs) GetCreatedAt() *time.Time { return j.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (j *Jobs) SetCreatedAt(stamp time.Time) { j.CreatedAt = &stamp }

// GetUpdatedAt will return the value of UpdatedAt.
func (j *Jobs) GetUpdatedAt() *time.Time { return j.UpdatedAt }

// SetUpdatedAt sets UpdatedAt to the provided value.
func (j *Jobs) SetUpdatedAt(stamp time.Time) { j.UpdatedAt = &stamp }

// GetDeletedAt will return the value of DeletedAt.
func (j *Jobs) GetDeletedAt() *time.Time { return j.DeletedAt }

// SetDeletedAt sets DeletedAt to the provided value.
func (j *Jobs) SetDeletedAt(stamp time.Time) { j.DeletedAt = &stamp }

// JobsTable is the name of the table in the DB.
const JobsTable = "`jobs`"

// JobsFields is a list of all columns in the DB table.
var JobsFields = []string{"name", "description", "created_at", "updated_at", "deleted_at"}

// JobsPrimaryFields are the primary key fields in the DB table.
var JobsPrimaryFields = []string{"name"}

// Logs generated for db table `logs`.
type Logs struct {
	// Name
	Name string `db:"name" json:"name"`

	// Stamp
	Stamp *time.Time `db:"stamp" json:"stamp"`

	// Duration
	Duration int64 `db:"duration" json:"duration"`

	// Output
	Output string `db:"output" json:"output"`

	// Exit Code
	ExitCode int64 `db:"exit_code" json:"exit_code"`

	// Created At
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

// GetName will return the value of Name.
func (l *Logs) GetName() string { return l.Name }

// SetName sets Name to the provided value.
func (l *Logs) SetName(val string) { l.Name = val }

// GetStamp will return the value of Stamp.
func (l *Logs) GetStamp() *time.Time { return l.Stamp }

// SetStamp sets Stamp to the provided value.
func (l *Logs) SetStamp(stamp time.Time) { l.Stamp = &stamp }

// GetDuration will return the value of Duration.
func (l *Logs) GetDuration() int64 { return l.Duration }

// SetDuration sets Duration to the provided value.
func (l *Logs) SetDuration(val int64) { l.Duration = val }

// GetOutput will return the value of Output.
func (l *Logs) GetOutput() string { return l.Output }

// SetOutput sets Output to the provided value.
func (l *Logs) SetOutput(val string) { l.Output = val }

// GetExitCode will return the value of ExitCode.
func (l *Logs) GetExitCode() int64 { return l.ExitCode }

// SetExitCode sets ExitCode to the provided value.
func (l *Logs) SetExitCode(val int64) { l.ExitCode = val }

// GetCreatedAt will return the value of CreatedAt.
func (l *Logs) GetCreatedAt() *time.Time { return l.CreatedAt }

// SetCreatedAt sets CreatedAt to the provided value.
func (l *Logs) SetCreatedAt(stamp time.Time) { l.CreatedAt = &stamp }

// LogsTable is the name of the table in the DB.
const LogsTable = "`logs`"

// LogsFields is a list of all columns in the DB table.
var LogsFields = []string{"name", "stamp", "duration", "output", "exit_code", "created_at"}

// LogsPrimaryFields are the primary key fields in the DB table.
var LogsPrimaryFields = []string{"name", "stamp"}

// Migrations generated for db table `migrations`.
type Migrations struct {
	// Project
	Project string `db:"project" json:"project"`

	// Filename
	Filename string `db:"filename" json:"filename"`

	// Statement Index
	StatementIndex int64 `db:"statement_index" json:"statement_index"`

	// Status
	Status string `db:"status" json:"status"`
}

// GetProject will return the value of Project.
func (m *Migrations) GetProject() string { return m.Project }

// SetProject sets Project to the provided value.
func (m *Migrations) SetProject(val string) { m.Project = val }

// GetFilename will return the value of Filename.
func (m *Migrations) GetFilename() string { return m.Filename }

// SetFilename sets Filename to the provided value.
func (m *Migrations) SetFilename(val string) { m.Filename = val }

// GetStatementIndex will return the value of StatementIndex.
func (m *Migrations) GetStatementIndex() int64 { return m.StatementIndex }

// SetStatementIndex sets StatementIndex to the provided value.
func (m *Migrations) SetStatementIndex(val int64) { m.StatementIndex = val }

// GetStatus will return the value of Status.
func (m *Migrations) GetStatus() string { return m.Status }

// SetStatus sets Status to the provided value.
func (m *Migrations) SetStatus(val string) { m.Status = val }

// MigrationsTable is the name of the table in the DB.
const MigrationsTable = "`migrations`"

// MigrationsFields is a list of all columns in the DB table.
var MigrationsFields = []string{"project", "filename", "statement_index", "status"}

// MigrationsPrimaryFields are the primary key fields in the DB table.
var MigrationsPrimaryFields = []string{"project", "filename"}

// Insert starts building an INSERT INTO query.
func (j *Jobs) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := JobsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (j *Jobs) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (j *Jobs) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobsTable}).Apply(opts...)
	cols := JobsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (j *Jobs) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: JobsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (l *Logs) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: LogsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := LogsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (l *Logs) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: LogsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (l *Logs) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: LogsTable}).Apply(opts...)
	cols := LogsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (l *Logs) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: LogsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Insert starts building an INSERT INTO query.
func (m *Migrations) Insert(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable, Statement: "INSERT INTO"}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	return fmt.Sprintf("%s %s (%s) VALUES (:%s)", cfg.Statement, cfg.Table, strings.Join(cols, ", "), strings.Join(cols, ", :"))
}

// Select starts building a SELECT query.
func (m *Migrations) Select(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := "*"
	if len(cfg.Columns) > 0 {
		cols = strings.Join(cfg.Columns, ", ")
	}
	query := fmt.Sprintf("SELECT %s FROM %s", cols, cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	if cfg.OrderBy != "" {
		query += " ORDER BY " + cfg.OrderBy
	}
	if cfg.LimitOffset > 0 {
		query += fmt.Sprintf(" LIMIT %d, %d", cfg.LimitStart, cfg.LimitOffset)
	}
	return query
}

// Update starts building a UPDATE query.
func (m *Migrations) Update(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	cols := MigrationsFields
	if len(cfg.Columns) > 0 {
		cols = cfg.Columns
	}
	setClause := ""
	for i, col := range cols {
		if i > 0 {
			setClause += ", "
		}
		setClause += col + "=:" + col
	}
	query := fmt.Sprintf("UPDATE %s SET %s", cfg.Table, setClause)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}

// Delete starts building a DELETE query.
func (m *Migrations) Delete(opts ...QueryOption) string {
	cfg := (&QueryConfig{Table: MigrationsTable}).Apply(opts...)
	query := fmt.Sprintf("DELETE FROM %s", cfg.Table)
	if cfg.Where != "" {
		query += " WHERE " + cfg.Where
	}
	return query
}
