workspace:
  base: /go-web-crontab

kind: pipeline
name: crust

steps:
- name: build
  image: golang:1.12-alpine
  pull: always
  environment:
    CGO_ENABLED: 0
    GOPROXY: https://proxy.golang.org
    GOOS: linux
    GOARCH: amd64
    CI: travis
  commands:
  - apk --no-cache add make git
  - go get -u github.com/goware/statik
  - statik -p db -m -Z -f -src=db/schema/mysql
  - make test
  - make build

services:
- name: webcron-db
  pull: always
  image: percona:8.0
  command: [ "--innodb_lock_wait_timeout=2" ]
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: bRxJ37sJ6Qu4
    MYSQL_DATABASE: webcron
    MYSQL_USER: webcron
    MYSQL_PASSWORD: webcron
