vars:
  name: webcron

jobs:
  default:
    desc: "Run stuff"
    passthru: true
    steps:
      - go fmt ./...
      - go mod tidy
      - goimports -w .
      - phpscript fmt ./frontend/
      - phpscript lint ./frontend/...
      - go install ./cmd/...
      - task: go:build

  run:
    desc: "Run webcron"
    tty: true
    steps:
      - PLATFORM_DB_CRONTAB='sqlite://webcron.db?_time_format=sqlite' webcron
