---
version: "3"

tasks:
  default:
    default: "Run stuff"
    cmds:
    - go fmt ./...
    - go test -timeout 5s -v -count 1 ./...

  test:
    desc: "Run tests"
    cmds:
      - docker compose up -d --wait
      - go test -v --tags=integration -count 1 ./...

  run:
    desc: "Run webcron"
    cmds:
      - go install ./cmd/...
      - webcron

  clean:
    desc: "Clean up docker"
    cmds:
      - docker compose down
      - docker system prune -f
